In [1]:
import pickle
import os
import numpy as np

## Data splitting

In [2]:
with open('test_dataset.pkl','rb') as f:
    dataset = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'test_dataset.pkl'

In [ ]:
x = np.array(dataset['features'])
np.array(x).shape

(14, 20, 64, 64, 3)

In [ ]:
y = dataset['labels']
y = []
for label in dataset['labels']:
    if(label == 'correct'):
        y.append(1)
    if(label == 'incorrect'):
        y.append(0)

In [ ]:
y = np.array(y)

In [ ]:
from keras.models import load_model

# Load the best model saved during training
best_model = load_model('../Final/30frame_best_model.h5')

In [ ]:
ypred = best_model.predict(x)

1/1 [==============================] - 1s 1s/step


In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Define the threshold
threshold = 0.5

# Convert sigmoid outputs to binary values
ypred = np.argmax(ypred,axis=1)
ypred

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1], dtype=int64)

In [ ]:
from sklearn.metrics import *

confusion_matrix(y,ypred)

array([[4, 3],
       [1, 6]], dtype=int64)