In [51]:
import pickle
import os
import numpy as np

## Data splitting

In [52]:
with open('test_dataset.pkl','rb') as f:
    dataset = pickle.load(f)

In [53]:
x = np.array(dataset['features'])
np.array(x).shape

(1, 12, 64, 64, 3)

In [54]:
y = dataset['labels']
y = []
for label in dataset['labels']:
    if(label == 'correct'):
        y.append(1)
    if(label == 'incorrect'):
        y.append(0)

In [55]:
y = np.array(y)

In [56]:
# from sklearn.model_selection import train_test_split
# xtrain, xtest, ytrain, ytest = train_test_split(np.array(dataset['features']),np.array(dataset['labels']), test_size=0.25, random_state=100)

## Training

In [57]:
# from keras.layers import Dense, ConvLSTM2D, MaxPooling3D, TimeDistributed, Dropout, Flatten
# from keras.models import Sequential
# from keras.callbacks import EarlyStopping

In [58]:
# def create_model():
#     model = Sequential()

#     model.add(ConvLSTM2D(filters=4, kernel_size=(3,3), activation='tanh', data_format='channels_last', recurrent_dropout=0.2, return_sequences=True,
#                          input_shape = (12,64,64,3)))
#     model.add(MaxPooling3D(pool_size=(1,2,2),padding='same', data_format='channels_last'))
#     model.add(TimeDistributed(Dropout(0.2)))

#     model.add(ConvLSTM2D(filters=8, kernel_size=(3,3), activation='tanh', data_format='channels_last', recurrent_dropout=0.2, return_sequences=True))
#     model.add(MaxPooling3D(pool_size=(1,2,2),padding='same', data_format='channels_last'))
#     model.add(TimeDistributed(Dropout(0.2)))

#     model.add(ConvLSTM2D(filters=14, kernel_size=(3,3), activation='tanh', data_format='channels_last', recurrent_dropout=0.2, return_sequences=True))
#     model.add(MaxPooling3D(pool_size=(1,2,2),padding='same', data_format='channels_last'))
#     model.add(TimeDistributed(Dropout(0.2)))

#     model.add(ConvLSTM2D(filters=14, kernel_size=(3,3), activation='tanh', data_format='channels_last', recurrent_dropout=0.2, return_sequences=True))
#     model.add(MaxPooling3D(pool_size=(1,2,2),padding='same', data_format='channels_last'))
#     model.add(TimeDistributed(Dropout(0.2)))

#     model.add(ConvLSTM2D(filters=16, kernel_size=(3,3), activation='tanh', data_format='channels_last', recurrent_dropout=0.2, return_sequences=True))
#     model.add(MaxPooling3D(pool_size=(1,2,2),padding='same', data_format='channels_last'))
    
#     model.add(Flatten())

#     model.add(Dense(1, activation='sigmoid'))

#     model.summary()
#     return model

In [59]:
# model = create_model()

In [60]:
# early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, mode='min', restore_best_weights=True)

# model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

# model.fit(xtrain, ytrain, epochs=50, batch_size=4, shuffle=True, callbacks=[early_stopping_callback], validation_split=0.2)

In [61]:
# from keras.callbacks import EarlyStopping, ModelCheckpoint


# # Define Early Stopping Callback
# early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, mode='min', restore_best_weights=True)

# # Define ModelCheckpoint Callback to save the model at the end of training
# model_checkpoint_callback = ModelCheckpoint(filepath='best_model.h5', save_best_only=True, save_weights_only=False, monitor='val_loss', mode='min')

# # Compile the model
# model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

# # Train the model with validation data and callbacks
# model.fit(xtrain, ytrain, epochs=50, batch_size=4, shuffle=True, callbacks=[early_stopping_callback, model_checkpoint_callback], validation_split=0.2)




In [62]:
from keras.models import load_model

# Load the best model saved during training
best_model = load_model('best_model.h5')

In [63]:
ypred = best_model.predict(x)

1/1 [==============================] - 1s 867ms/step


In [64]:
y

array([0])

In [65]:
# Define the threshold
threshold = 0.5

# Convert sigmoid outputs to binary values
ypred = (ypred >= threshold).astype(int)
ypred

array([[0]])

In [66]:
from sklearn.metrics import *

confusion_matrix(y,ypred)

d:\miniconda\envs\ml\lib\site-packages\sklearn\metrics\_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


array([[1]], dtype=int64)