In [1]:
import pickle
import os
import numpy as np

## Data splitting

In [2]:
with open('test_dataset.pkl','rb') as f:
    dataset = pickle.load(f)

In [3]:
x = np.array(dataset['features'])
np.array(x).shape

(14, 30, 64, 64, 3)

In [4]:
y = dataset['labels']
y = []
for label in dataset['labels']:
    if(label == 'correct'):
        y.append(1)
    if(label == 'incorrect'):
        y.append(0)

In [5]:
y = np.array(y)

In [6]:
from keras.models import load_model

# Load the best model saved during training
best_model = load_model('30frame_best_model_large_box_Anish.h5')

In [7]:
ypred = best_model.predict(x)

1/1 [==============================] - 6s 6s/step


In [8]:
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Define the threshold
threshold = 0.5

# Convert sigmoid outputs to binary values
ypred = np.argmax(ypred,axis=1)
ypred

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [10]:
from sklearn.metrics import *

confusion_matrix(y,ypred)

array([[5, 2],
       [4, 3]], dtype=int64)