In [136]:
import pickle
import os
import numpy as np

## Data splitting

In [137]:
with open('test_dataset.pkl','rb') as f:
    dataset = pickle.load(f)

In [138]:
x = np.array(dataset['features'])
np.array(x).shape

(14, 20, 64, 64, 3)

In [139]:
y = dataset['labels']
y = []
for label in dataset['labels']:
    if(label == 'correct'):
        y.append(1)
    if(label == 'incorrect'):
        y.append(0)

In [140]:
y = np.array(y)

In [141]:
from keras.models import load_model

# Load the best model saved during training
best_model = load_model('retrain_best_model.h5')

In [142]:
ypred = best_model.predict(x)

1/1 [==============================] - 1s 1s/step


In [143]:
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [144]:
# Define the threshold
threshold = 0.5

# Convert sigmoid outputs to binary values
ypred = np.argmax(ypred,axis=1)
ypred

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1], dtype=int64)

In [145]:
from sklearn.metrics import *

confusion_matrix(y,ypred)

array([[4, 3],
       [1, 6]], dtype=int64)